title: "Ming Chu"
description: "Professional blending frontline support with data-driven innovation to improve patient care."
logo: /assets/img/headshot.png
url: "https://mingislight.com"

# Contact & Links
location: "Bozeman, Montana"
email: "mingcomputerscience@gmail.com"
linkedin_url: "https://www.linkedin.com/in/mingislight"

# Theme & Plugins
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
