title: "Ming Chu"
description: "Healthcare IT and Machine Learning Researcher"
logo: /assets/img/headshot.png
url: "https://mingislight.com"

# Social sharing image (default OG/Twitter card)
social_image: /assets/img/social-card.png

# Contact & Links
location: "Bozeman, Montana"
linkedin_url: "https://www.linkedin.com/in/mingislight"

# Theme & Plugins
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
